const data = {
    getAll: [
        {
            updated: 1587140275989,
            cases: 2181308,
            todayCases: 95022,
            deaths: 145471,
            todayDeaths: 6996,
            recovered: 547069,
            active: 1488768,
            critical: 56602,
            casesPerOneMillion: 280,
            deathsPerOneMillion: 18,
            tests: 18215929,
            testsPerOneMillion: 2338.3,
            affectedCountries: 212,
        },
    ],

    getAllCountries: [
        {
            updated: 1587140875524,
            country: "Afghanistan",
            countryInfo: {
                _id: 4,
                iso2: "AF",
                iso3: "AFG",
                lat: 33,
                long: 65,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/af.png",
            },
            cases: 840,
            todayCases: 56,
            deaths: 30,
            todayDeaths: 5,
            recovered: 54,
            active: 756,
            critical: 0,
            casesPerOneMillion: 22,
            deathsPerOneMillion: 0,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875533,
            country: "Albania",
            countryInfo: {
                _id: 8,
                iso2: "AL",
                iso3: "ALB",
                lat: 41,
                long: 20,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/al.png",
            },
            cases: 518,
            todayCases: 24,
            deaths: 26,
            todayDeaths: 1,
            recovered: 277,
            active: 215,
            critical: 5,
            casesPerOneMillion: 180,
            deathsPerOneMillion: 9,
            tests: 4827,
            testsPerOneMillion: 1677,
        },
        {
            updated: 1587140875510,
            country: "Algeria",
            countryInfo: {
                _id: 12,
                iso2: "DZ",
                iso3: "DZA",
                lat: 28,
                long: 3,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/dz.png",
            },
            cases: 2268,
            todayCases: 108,
            deaths: 348,
            todayDeaths: 12,
            recovered: 783,
            active: 1137,
            critical: 60,
            casesPerOneMillion: 52,
            deathsPerOneMillion: 8,
            tests: 3359,
            testsPerOneMillion: 77,
        },
        {
            updated: 1587140875529,
            country: "Andorra",
            countryInfo: {
                _id: 20,
                iso2: "AD",
                iso3: "AND",
                lat: 42.5,
                long: 1.6,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ad.png",
            },
            cases: 673,
            todayCases: 0,
            deaths: 33,
            todayDeaths: 0,
            recovered: 169,
            active: 471,
            critical: 17,
            casesPerOneMillion: 8710,
            deathsPerOneMillion: 427,
            tests: 1673,
            testsPerOneMillion: 21653,
        },
        {
            updated: 1587140875574,
            country: "Angola",
            countryInfo: {
                _id: 24,
                iso2: "AO",
                iso3: "AGO",
                lat: -12.5,
                long: 18.5,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ao.png",
            },
            cases: 19,
            todayCases: 0,
            deaths: 2,
            todayDeaths: 0,
            recovered: 5,
            active: 12,
            critical: 0,
            casesPerOneMillion: 0,
            deathsPerOneMillion: 0,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875596,
            country: "Anguilla",
            countryInfo: {
                _id: 660,
                iso2: "AI",
                iso3: "AIA",
                lat: 18.25,
                long: -63.1667,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ai.png",
            },
            cases: 3,
            todayCases: 0,
            deaths: 0,
            todayDeaths: 0,
            recovered: 1,
            active: 2,
            critical: 0,
            casesPerOneMillion: 200,
            deathsPerOneMillion: 0,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875572,
            country: "Antigua and Barbuda",
            countryInfo: {
                _id: 28,
                iso2: "AG",
                iso3: "ATG",
                lat: 17.05,
                long: -61.8,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ag.png",
            },
            cases: 23,
            todayCases: 0,
            deaths: 3,
            todayDeaths: 1,
            recovered: 3,
            active: 17,
            critical: 1,
            casesPerOneMillion: 235,
            deathsPerOneMillion: 31,
            tests: 73,
            testsPerOneMillion: 745,
        },
        {
            updated: 1587140875508,
            country: "Argentina",
            countryInfo: {
                _id: 32,
                iso2: "AR",
                iso3: "ARG",
                lat: -34,
                long: -64,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ar.png",
            },
            cases: 2669,
            todayCases: 98,
            deaths: 122,
            todayDeaths: 10,
            recovered: 631,
            active: 1916,
            critical: 121,
            casesPerOneMillion: 59,
            deathsPerOneMillion: 3,
            tests: 26457,
            testsPerOneMillion: 585,
        },
        {
            updated: 1587140875519,
            country: "Armenia",
            countryInfo: {
                _id: 51,
                iso2: "AM",
                iso3: "ARM",
                lat: 40,
                long: 45,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/am.png",
            },
            cases: 1159,
            todayCases: 48,
            deaths: 18,
            todayDeaths: 1,
            recovered: 358,
            active: 783,
            critical: 30,
            casesPerOneMillion: 391,
            deathsPerOneMillion: 6,
            tests: 9632,
            testsPerOneMillion: 3250,
        },
        {
            updated: 1587140875555,
            country: "Aruba",
            countryInfo: {
                _id: 533,
                iso2: "AW",
                iso3: "ABW",
                lat: 12.5,
                long: -69.9667,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/aw.png",
            },
            cases: 95,
            todayCases: 2,
            deaths: 2,
            todayDeaths: 1,
            recovered: 39,
            active: 54,
            critical: 1,
            casesPerOneMillion: 890,
            deathsPerOneMillion: 19,
            tests: 1237,
            testsPerOneMillion: 11586,
        },
        {
            updated: 1587140875493,
            country: "Australia",
            countryInfo: {
                _id: 36,
                iso2: "AU",
                iso3: "AUS",
                lat: -27,
                long: 133,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/au.png",
            },
            cases: 6468,
            todayCases: 21,
            deaths: 63,
            todayDeaths: 0,
            recovered: 3747,
            active: 2658,
            critical: 66,
            casesPerOneMillion: 254,
            deathsPerOneMillion: 2,
            tests: 380003,
            testsPerOneMillion: 14902,
        },
        {
            updated: 1587140875483,
            country: "Austria",
            countryInfo: {
                _id: 40,
                iso2: "AT",
                iso3: "AUT",
                lat: 47.3333,
                long: 13.3333,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/at.png",
            },
            cases: 14476,
            todayCases: 126,
            deaths: 410,
            todayDeaths: 17,
            recovered: 8986,
            active: 5080,
            critical: 238,
            casesPerOneMillion: 1607,
            deathsPerOneMillion: 46,
            tests: 162816,
            testsPerOneMillion: 18078,
        },
        {
            updated: 1587140875517,
            country: "Azerbaijan",
            countryInfo: {
                _id: 31,
                iso2: "AZ",
                iso3: "AZE",
                lat: 40.5,
                long: 47.5,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/az.png",
            },
            cases: 1283,
            todayCases: 30,
            deaths: 15,
            todayDeaths: 2,
            recovered: 460,
            active: 808,
            critical: 28,
            casesPerOneMillion: 127,
            deathsPerOneMillion: 1,
            tests: 75397,
            testsPerOneMillion: 7436,
        },
        {
            updated: 1587140875564,
            country: "Bahamas",
            countryInfo: {
                _id: 44,
                iso2: "BS",
                iso3: "BHS",
                lat: 24.25,
                long: -76,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bs.png",
            },
            cases: 53,
            todayCases: 0,
            deaths: 8,
            todayDeaths: 0,
            recovered: 6,
            active: 39,
            critical: 1,
            casesPerOneMillion: 135,
            deathsPerOneMillion: 20,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875512,
            country: "Bahrain",
            countryInfo: {
                _id: 48,
                iso2: "BH",
                iso3: "BHR",
                lat: 26,
                long: 50.55,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bh.png",
            },
            cases: 1700,
            todayCases: 29,
            deaths: 7,
            todayDeaths: 0,
            recovered: 703,
            active: 990,
            critical: 3,
            casesPerOneMillion: 999,
            deathsPerOneMillion: 4,
            tests: 76630,
            testsPerOneMillion: 45035,
        },
        {
            updated: 1587140875513,
            country: "Bangladesh",
            countryInfo: {
                _id: 50,
                iso2: "BD",
                iso3: "BGD",
                lat: 24,
                long: 90,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bd.png",
            },
            cases: 1572,
            todayCases: 341,
            deaths: 60,
            todayDeaths: 10,
            recovered: 49,
            active: 1463,
            critical: 1,
            casesPerOneMillion: 10,
            deathsPerOneMillion: 0,
            tests: 17003,
            testsPerOneMillion: 103,
        },
        {
            updated: 1587140875560,
            country: "Barbados",
            countryInfo: {
                _id: 52,
                iso2: "BB",
                iso3: "BRB",
                lat: 13.1667,
                long: -59.5333,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bb.png",
            },
            cases: 75,
            todayCases: 2,
            deaths: 5,
            todayDeaths: 0,
            recovered: 15,
            active: 55,
            critical: 4,
            casesPerOneMillion: 261,
            deathsPerOneMillion: 17,
            tests: 900,
            testsPerOneMillion: 3132,
        },
        {
            updated: 1587140875502,
            country: "Belarus",
            countryInfo: {
                _id: 112,
                iso2: "BY",
                iso3: "BLR",
                lat: 53,
                long: 28,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/by.png",
            },
            cases: 4204,
            todayCases: 476,
            deaths: 40,
            todayDeaths: 4,
            recovered: 203,
            active: 3961,
            critical: 65,
            casesPerOneMillion: 445,
            deathsPerOneMillion: 4,
            tests: 81246,
            testsPerOneMillion: 8598,
        },
        {
            updated: 1587140875478,
            country: "Belgium",
            countryInfo: {
                _id: 56,
                iso2: "BE",
                iso3: "BEL",
                lat: 50.8333,
                long: 4,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/be.png",
            },
            cases: 34809,
            todayCases: 1236,
            deaths: 4857,
            todayDeaths: 417,
            recovered: 7562,
            active: 22390,
            critical: 1182,
            casesPerOneMillion: 3003,
            deathsPerOneMillion: 419,
            tests: 134303,
            testsPerOneMillion: 11588,
        },
        {
            updated: 1587140875576,
            country: "Belize",
            countryInfo: {
                _id: 84,
                iso2: "BZ",
                iso3: "BLZ",
                lat: 17.25,
                long: -88.75,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bz.png",
            },
            cases: 18,
            todayCases: 0,
            deaths: 2,
            todayDeaths: 0,
            recovered: 0,
            active: 16,
            critical: 1,
            casesPerOneMillion: 45,
            deathsPerOneMillion: 5,
            tests: 567,
            testsPerOneMillion: 1426,
        },
        {
            updated: 1587140875568,
            country: "Benin",
            countryInfo: {
                _id: 204,
                iso2: "BJ",
                iso3: "BEN",
                lat: 9.5,
                long: 2.25,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bj.png",
            },
            cases: 35,
            todayCases: 0,
            deaths: 1,
            todayDeaths: 0,
            recovered: 18,
            active: 16,
            critical: 0,
            casesPerOneMillion: 3,
            deathsPerOneMillion: 0,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875558,
            country: "Bermuda",
            countryInfo: {
                _id: 60,
                iso2: "BM",
                iso3: "BMU",
                lat: 32.3333,
                long: -64.75,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bm.png",
            },
            cases: 81,
            todayCases: 0,
            deaths: 5,
            todayDeaths: 0,
            recovered: 33,
            active: 43,
            critical: 3,
            casesPerOneMillion: 1301,
            deathsPerOneMillion: 80,
            tests: 527,
            testsPerOneMillion: 8462,
        },
        {
            updated: 1587140875594,
            country: "Bhutan",
            countryInfo: {
                _id: 64,
                iso2: "BT",
                iso3: "BTN",
                lat: 27.5,
                long: 90.5,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bt.png",
            },
            cases: 5,
            todayCases: 0,
            deaths: 0,
            todayDeaths: 0,
            recovered: 2,
            active: 3,
            critical: 0,
            casesPerOneMillion: 6,
            deathsPerOneMillion: 0,
            tests: 1166,
            testsPerOneMillion: 1511,
        },
        {
            updated: 1587140875536,
            country: "Bolivia",
            countryInfo: {
                _id: 68,
                iso2: "BO",
                iso3: "BOL",
                lat: -17,
                long: -65,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bo.png",
            },
            cases: 441,
            todayCases: 44,
            deaths: 29,
            todayDeaths: 1,
            recovered: 14,
            active: 398,
            critical: 3,
            casesPerOneMillion: 38,
            deathsPerOneMillion: 2,
            tests: 2185,
            testsPerOneMillion: 187,
        },
        {
            updated: 1587140875518,
            country: "Bosnia",
            countryInfo: {
                _id: 70,
                iso2: "BA",
                iso3: "BIH",
                lat: 44,
                long: 18,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ba.png",
            },
            cases: 1167,
            todayCases: 57,
            deaths: 43,
            todayDeaths: 2,
            recovered: 277,
            active: 847,
            critical: 4,
            casesPerOneMillion: 356,
            deathsPerOneMillion: 13,
            tests: 14743,
            testsPerOneMillion: 4494,
        },
        {
            updated: 1587140875581,
            country: "Botswana",
            countryInfo: {
                _id: 72,
                iso2: "BW",
                iso3: "BWA",
                lat: -22,
                long: 24,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bw.png",
            },
            cases: 15,
            todayCases: 2,
            deaths: 1,
            todayDeaths: 0,
            recovered: 0,
            active: 14,
            critical: 0,
            casesPerOneMillion: 6,
            deathsPerOneMillion: 0,
            tests: 3441,
            testsPerOneMillion: 1463,
        },
        {
            updated: 1587140875479,
            country: "Brazil",
            countryInfo: {
                _id: 76,
                iso2: "BR",
                iso3: "BRA",
                lat: -10,
                long: -55,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/br.png",
            },
            cases: 30683,
            todayCases: 2073,
            deaths: 1947,
            todayDeaths: 190,
            recovered: 14026,
            active: 14710,
            critical: 6634,
            casesPerOneMillion: 144,
            deathsPerOneMillion: 9,
            tests: 62985,
            testsPerOneMillion: 296,
        },
        {
            updated: 1587140875596,
            country: "British Virgin Islands",
            countryInfo: {
                _id: 92,
                iso2: "VG",
                iso3: "VGB",
                lat: 18.5,
                long: -64.5,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/vg.png",
            },
            cases: 3,
            todayCases: 0,
            deaths: 0,
            todayDeaths: 0,
            recovered: 2,
            active: 1,
            critical: 0,
            casesPerOneMillion: 99,
            deathsPerOneMillion: 0,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875551,
            country: "Brunei",
            countryInfo: {
                _id: 96,
                iso2: "BN",
                iso3: "BRN",
                lat: 4.5,
                long: 114.6667,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bn.png",
            },
            cases: 136,
            todayCases: 0,
            deaths: 1,
            todayDeaths: 0,
            recovered: 108,
            active: 27,
            critical: 2,
            casesPerOneMillion: 311,
            deathsPerOneMillion: 2,
            tests: 10826,
            testsPerOneMillion: 24746,
        },
        {
            updated: 1587140875526,
            country: "Bulgaria",
            countryInfo: {
                _id: 100,
                iso2: "BG",
                iso3: "BGR",
                lat: 43,
                long: 25,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bg.png",
            },
            cases: 800,
            todayCases: 53,
            deaths: 38,
            todayDeaths: 2,
            recovered: 122,
            active: 640,
            critical: 37,
            casesPerOneMillion: 115,
            deathsPerOneMillion: 5,
            tests: 18502,
            testsPerOneMillion: 2663,
        },
        {
            updated: 1587140875532,
            country: "Burkina Faso",
            countryInfo: {
                _id: 854,
                iso2: "BF",
                iso3: "BFA",
                lat: 13,
                long: -2,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bf.png",
            },
            cases: 546,
            todayCases: 4,
            deaths: 32,
            todayDeaths: 0,
            recovered: 257,
            active: 257,
            critical: 0,
            casesPerOneMillion: 26,
            deathsPerOneMillion: 2,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875594,
            country: "Burundi",
            countryInfo: {
                _id: 108,
                iso2: "BI",
                iso3: "BDI",
                lat: -3.5,
                long: 30,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bi.png",
            },
            cases: 5,
            todayCases: 0,
            deaths: 1,
            todayDeaths: 0,
            recovered: 0,
            active: 4,
            critical: 0,
            casesPerOneMillion: 0,
            deathsPerOneMillion: 0,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875562,
            country: "Cabo Verde",
            countryInfo: {
                _id: 132,
                iso2: "CV",
                iso3: "CPV",
                lat: 16,
                long: -24,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cv.png",
            },
            cases: 56,
            todayCases: 0,
            deaths: 1,
            todayDeaths: 0,
            recovered: 1,
            active: 54,
            critical: 0,
            casesPerOneMillion: 101,
            deathsPerOneMillion: 2,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875552,
            country: "Cambodia",
            countryInfo: {
                _id: 116,
                iso2: "KH",
                iso3: "KHM",
                lat: 13,
                long: 105,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/kh.png",
            },
            cases: 122,
            todayCases: 0,
            deaths: 0,
            todayDeaths: 0,
            recovered: 98,
            active: 24,
            critical: 1,
            casesPerOneMillion: 7,
            deathsPerOneMillion: 0,
            tests: 5768,
            testsPerOneMillion: 345,
        },
        {
            updated: 1587140875521,
            country: "Cameroon",
            countryInfo: {
                _id: 120,
                iso2: "CM",
                iso3: "CMR",
                lat: 6,
                long: 12,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cm.png",
            },
            cases: 996,
            todayCases: 148,
            deaths: 22,
            todayDeaths: 5,
            recovered: 164,
            active: 810,
            critical: 0,
            casesPerOneMillion: 38,
            deathsPerOneMillion: 0,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875480,
            country: "Canada",
            countryInfo: {
                _id: 124,
                iso2: "CA",
                iso3: "CAN",
                lat: 60,
                long: -95,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ca.png",
            },
            cases: 30106,
            todayCases: 1727,
            deaths: 1195,
            todayDeaths: 185,
            recovered: 9729,
            active: 19182,
            critical: 557,
            casesPerOneMillion: 798,
            deathsPerOneMillion: 32,
            tests: 487625,
            testsPerOneMillion: 12920,
        },
        {
            updated: 1587140875597,
            country: "Caribbean Netherlands",
            countryInfo: {
                _id: 535,
                iso2: "BQ",
                iso3: "BES",
                lat: 12.2,
                long: -68.26,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bq.png",
            },
            cases: 3,
            todayCases: 0,
            deaths: 0,
            todayDeaths: 0,
            recovered: 0,
            active: 3,
            critical: 0,
            casesPerOneMillion: 114,
            deathsPerOneMillion: 0,
            tests: 10,
            testsPerOneMillion: 381,
        },
        {
            updated: 1587140875561,
            country: "Cayman Islands",
            countryInfo: {
                _id: 136,
                iso2: "KY",
                iso3: "CYM",
                lat: 19.5,
                long: -80.5,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ky.png",
            },
            cases: 60,
            todayCases: 0,
            deaths: 1,
            todayDeaths: 0,
            recovered: 6,
            active: 53,
            critical: 3,
            casesPerOneMillion: 913,
            deathsPerOneMillion: 15,
            tests: 636,
            testsPerOneMillion: 9677,
        },
        {
            updated: 1587140875585,
            country: "Central African Republic",
            countryInfo: {
                _id: 140,
                iso2: "CF",
                iso3: "CAF",
                lat: 7,
                long: 21,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cf.png",
            },
            cases: 12,
            todayCases: 0,
            deaths: 0,
            todayDeaths: 0,
            recovered: 4,
            active: 8,
            critical: 0,
            casesPerOneMillion: 2,
            deathsPerOneMillion: 0,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875571,
            country: "Chad",
            countryInfo: {
                _id: 148,
                iso2: "TD",
                iso3: "TCD",
                lat: 15,
                long: 19,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/td.png",
            },
            cases: 27,
            todayCases: 4,
            deaths: 0,
            todayDeaths: 0,
            recovered: 5,
            active: 22,
            critical: 0,
            casesPerOneMillion: 2,
            deathsPerOneMillion: 0,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875535,
            country: "Channel Islands",
            countryInfo: {
                _id: 832,
                iso2: "JE",
                iso3: "JEY",
                lat: 49.21,
                long: -2.13,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/je.png",
            },
            cases: 457,
            todayCases: 10,
            deaths: 19,
            todayDeaths: 4,
            recovered: 73,
            active: 365,
            critical: 0,
            casesPerOneMillion: 2629,
            deathsPerOneMillion: 109,
            tests: 3320,
            testsPerOneMillion: 19095,
        },
        {
            updated: 1587140875488,
            country: "Chile",
            countryInfo: {
                _id: 152,
                iso2: "CL",
                iso3: "CHL",
                lat: -30,
                long: -71,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cl.png",
            },
            cases: 8807,
            todayCases: 534,
            deaths: 105,
            todayDeaths: 11,
            recovered: 3299,
            active: 5403,
            critical: 384,
            casesPerOneMillion: 461,
            deathsPerOneMillion: 5,
            tests: 98424,
            testsPerOneMillion: 5149,
        },
        {
            updated: 1587140875471,
            country: "China",
            countryInfo: {
                _id: 156,
                iso2: "CN",
                iso3: "CHN",
                lat: 35,
                long: 105,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cn.png",
            },
            cases: 82341,
            todayCases: 46,
            deaths: 3342,
            todayDeaths: 0,
            recovered: 77892,
            active: 1107,
            critical: 95,
            casesPerOneMillion: 57,
            deathsPerOneMillion: 2,
            tests: 0,
            testsPerOneMillion: 0,
        },
        {
            updated: 1587140875506,
            country: "Colombia",
            countryInfo: {
                _id: 170,
                iso2: "CO",
                iso3: "COL",
                lat: 4,
                long: -72,
                flag: "https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/co.png",
            },
            cases: 3233,
            todayCases: 128,
            deaths: 144,
            todayDeaths: 13,
            recovered: 550,
            active: 2539,
            critical: 98,
            casesPerOneMillion: 64,
            deathsPerOneMillion: 3,
            tests: 52085,
            testsPerOneMillion: 1024,
        },
    ],
};
export default data;
